id: A9C3C0F98
title: Guru Sādhana of the Omniscient Dolpopa
type: translation
pechas:
- IDDA10D24
- I046A4CB6
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:44:51.924162
  last_modified_at: 2023-01-04 11:44:51.924167
  collections:
  - Dolpopa Sherab Gyaltsen
  - Works of Tibetan Masters
alignment_to_base:
  IDDA10D24/EF6E: 07B1
  I046A4CB6/6466: 07B1
